spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/banquito
      auto-index-creation: true

springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_1
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    syntax-highlight:
      activated: true
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  writer-with-default-pretty-printer: true

logging:
  level:
    com.banquito.branch: INFO
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 